#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = trace-mem-hier base-trace-mem-hier

SRC_FILES = trace.c

MODULE_LDFLAGS = $(LIBZ)

SIMICS_API = strict
THREAD_SAFE = yes

include $(MODULE_MAKEFILE)
