#!/bin/bash

IDDIR=id
IDEXE=landslide-id

if [ ! -d "pebsim" -o ! -d "work" ]; then
	echo -e "\033[01;31m$0 must be run from the root of the landslide repository.\033[00m"
	exit 1
fi

if [ ! -f "$IDDIR/$IDEXE" ]; then
	echo -e "\033[01;31mp2-setup.sh was not run or did not succeed.\033[00m"
	exit 1
fi

SUFFIX=`date +%Y%m%d%H%M%S`

CMDLINE_OPTION_FILE=`mktemp "ls-id-options-$SUFFIX.cfg.XXXXXXXX"`
echo "$@" > $CMDLINE_OPTION_FILE

WRAPPER_LOG="ls-id-log-$SUFFIX.log"

ORIGDIR="$PWD"
cd "$IDDIR"
./$IDEXE -L $WRAPPER_LOG "$@"
RV=$?

cd "$ORIGDIR"

ID_EXIT_USAGE=2
ID_EXIT_CTRL_C=3

if [ "$RV" = "$ID_EXIT_USAGE" ]; then
	exit $RV
elif [ "$RV" = "$ID_EXIT_CTRL_C" ]; then
	reset -I
	echo
fi

echo -e "\033[01;33mSaving results. Please be patient.\033[00m"

for logfile in id/ls*log*; do
	gzip -q $logfile
done

SNAPSHOT_DIR="/afs/cs.cmu.edu/academic/class/15410-s16/user/$USER/mygroup/landslide/"
TEMP_SNAP_DIR="/dev/shm"
SNAPSHOT_NAME="ls-snap-$USER-$SUFFIX.tar.bz2"
umask 077
tar cvjf "$TEMP_SNAP_DIR/$SNAPSHOT_NAME" \
	--exclude="pebsim/p2-basecode/410user/*" \
	--exclude="pebsim/p2-basecode/410kern/*" \
	--exclude="pebsim/p2-basecode/temp/*" \
	--exclude=".git/*" \
	--exclude="work/*" \
	--exclude="tests/*" \
	--exclude="*.o" \
	--exclude="*.a" \
	--exclude="*.bz2" \
	--exclude="*.dep" \
	--exclude="*.py" \
	--exclude="*.pyc" \
	--exclude="*landslide-id" \
	--exclude="*kernel" \
	--exclude="*bootfd.img" \
	--exclude="*kernel.strip" \
	--exclude="*kernel.log" \
	"./" >/dev/null
mv "$TEMP_SNAP_DIR/$SNAPSHOT_NAME" "$SNAPSHOT_DIR"
MV_RV=$?
if [ "$MV_RV" != "0" ]; then
	echo -e "\033[01;31mFailed to save snapshot ($TEMP_SNAP_DIR/$SNAPSHOT_NAME) into 410 AFS space ($SNAPSHOT_DIR). Please email Ben <bblum@cs.cmu.edu> for support, including this snapshot as an attachment."
	echo -e "\033[00m(landslide's exit code was $RV)"
	exit 1
fi

exit $RV
