/* args_c0ffi.c
 * This file automatically generated by the command 
 * 'wrappergen args' - editing is probably bad.
 * 
 * The call to wrappergen was likely probably by 
 * 'make libs/args', which in turn was likely
 * invoked by 'make libs'. */

#include <stdint.h>
#include <c0runtime.h>

/* Headers */

void args_flag(c0_string name, bool * ptr);
void args_int(c0_string name, int * ptr);
void args_string(c0_string name, c0_string * ptr);
struct args{
  int argc;
  c0_array * argv;
};
typedef struct args * args_t;
args_t args_parse();

/* Wrappers */

void *__c0ffi_args_flag(void **args) {
  args_flag((c0_string) args[0], (bool *) args[1]);
  return NULL;
}

void *__c0ffi_args_int(void **args) {
  args_int((c0_string) args[0], (int *) args[1]);
  return NULL;
}

void *__c0ffi_args_string(void **args) {
  args_string((c0_string) args[0], (c0_string *) args[1]);
  return NULL;
}

void *__c0ffi_args_parse(void **args) {
  (void) args; /* suppress error */
  return (void *) args_parse();
}

