// This file automatically generated by wrappergen
// Source: libs/conio/conio.h0

#include <stdint.h>
#include <c0runtime.h>

void print(c0_string s);
void println(c0_string s);
void printint(int i);
void printbool(bool b);
void printchar(c0_char c);
c0_string readline();
void error(c0_string s);

void *__c0ffi_print(void **args) {
  print((c0_string) args[0]);
  return NULL;
}

void *__c0ffi_println(void **args) {
  println((c0_string) args[0]);
  return NULL;
}

void *__c0ffi_printint(void **args) {
  printint((int) (intptr_t) args[0]);
  return NULL;
}

void *__c0ffi_printbool(void **args) {
  printbool((bool) (intptr_t) args[0]);
  return NULL;
}

void *__c0ffi_printchar(void **args) {
  printchar((c0_char) (intptr_t) args[0]);
  return NULL;
}

void *__c0ffi_readline(void **args) {
  (void) args; /* suppress error */
  return (void *) readline();
}

void *__c0ffi_error(void **args) {
  error((c0_string) args[0]);
  return NULL;
}
