/* string_c0ffi.c
 * This file automatically generated by the command 
 * 'wrappergen string' - editing is probably bad.
 * 
 * The call to wrappergen was likely probably by 
 * 'make libs/string', which in turn was likely
 * invoked by 'make libs'. */

#include <stdint.h>
#include <c0runtime.h>

/* Headers */

int string_length(c0_string s);
c0_char string_charat(c0_string s, int idx);
c0_string string_join(c0_string a, c0_string b);
c0_string string_sub(c0_string a, int start, int end);
bool string_equal(c0_string a, c0_string b);
int string_compare(c0_string a, c0_string b);
c0_string string_fromint(int i);
c0_string string_frombool(bool b);
c0_string string_fromchar(c0_char c);
c0_string string_tolower(c0_string s);
bool string_terminated(c0_array * A, int n);
c0_array * string_to_chararray(c0_string s);
c0_string string_from_chararray(c0_array * A);
int char_ord(c0_char c);
c0_char char_chr(int n);

/* Wrappers */

void *__c0ffi_string_length(void **args) {
  return (void *) (intptr_t) string_length((c0_string) args[0]);
}

void *__c0ffi_string_charat(void **args) {
  return (void *) (intptr_t) string_charat((c0_string) args[0],
  					   (int) (intptr_t) args[1]);
}

void *__c0ffi_string_join(void **args) {
  return (void *) string_join((c0_string) args[0], (c0_string) args[1]);
}

void *__c0ffi_string_sub(void **args) {
  return (void *) string_sub((c0_string) args[0], (int) (intptr_t) args[1],
  			     (int) (intptr_t) args[2]);
}

void *__c0ffi_string_equal(void **args) {
  return (void *) (intptr_t) string_equal((c0_string) args[0],
  					  (c0_string) args[1]);
}

void *__c0ffi_string_compare(void **args) {
  return (void *) (intptr_t) string_compare((c0_string) args[0],
  					    (c0_string) args[1]);
}

void *__c0ffi_string_fromint(void **args) {
  return (void *) string_fromint((int) (intptr_t) args[0]);
}

void *__c0ffi_string_frombool(void **args) {
  return (void *) string_frombool((bool) (intptr_t) args[0]);
}

void *__c0ffi_string_fromchar(void **args) {
  return (void *) string_fromchar((c0_char) (intptr_t) args[0]);
}

void *__c0ffi_string_tolower(void **args) {
  return (void *) string_tolower((c0_string) args[0]);
}

void *__c0ffi_string_terminated(void **args) {
  return (void *) (intptr_t) string_terminated((c0_array *) args[0],
  					       (int) (intptr_t) args[1]);
}

void *__c0ffi_string_to_chararray(void **args) {
  return (void *) string_to_chararray((c0_string) args[0]);
}

void *__c0ffi_string_from_chararray(void **args) {
  return (void *) string_from_chararray((c0_array *) args[0]);
}

void *__c0ffi_char_ord(void **args) {
  return (void *) (intptr_t) char_ord((c0_char) (intptr_t) args[0]);
}

void *__c0ffi_char_chr(void **args) {
  return (void *) (intptr_t) char_chr((int) (intptr_t) args[0]);
}

