#!/bin/sh
# this file will be overwritten by the workspace setup script
SIMICS_BASE_PACKAGE="/afs/andrew.cmu.edu/usr12/bblum/410/simics/simics-4.0.60"
export SIMICS_BASE_PACKAGE
if [ -f "/afs/andrew.cmu.edu/usr12/bblum/masters/work/.package-list" ]; then
    exec "/afs/andrew.cmu.edu/usr12/bblum/410/simics/simics-4.0.60/bin/simics-gui" -package-list "/afs/andrew.cmu.edu/usr12/bblum/masters/work/.package-list" -workspace "/afs/andrew.cmu.edu/usr12/bblum/masters/work" ${1+"$@"}
else
    exec "/afs/andrew.cmu.edu/usr12/bblum/410/simics/simics-4.0.60/bin/simics-gui" -workspace "/afs/andrew.cmu.edu/usr12/bblum/masters/work" ${1+"$@"}
fi
