#!/bin/sh

if [ "`pwd | sed 's/.*\///'`" != "pebsim" ]; then
	echo -e "\033[01;31m$0 must be run from the pebsim directory.\033[00m"
	exit 1
fi

export LANDSLIDE_CONFIG=config.landslide

export VTECH_LICENSE_FILE=/afs/cs.cmu.edu/academic/class/15410-f13/simics-4.0.60/simics-4.0.60/licenses/1license.lic

./build.sh && time ./simics4
