#!/bin/sh

if [ "`pwd | sed 's/.*\///'`" != "pebsim" ]; then
	echo -e "\033[01;31m$0 must be run from the pebsim directory.\033[00m"
	exit 1
fi

if [ ! -z "$1" ]; then
	export LANDSLIDE_ID_CONFIG="$1"
else
	export LANDSLIDE_ID_CONFIG=
fi

export LANDSLIDE_CONFIG=config.landslide

export VTECH_LICENSE_FILE=/afs/cs.cmu.edu/academic/class/15410-s15/simics-4.0.60/simics-4.0.60/licenses/1license.lic

# a frumious hack
export KERNEL_SOURCE_DIR=`grep KERNEL_SOURCE_DIR $LANDSLIDE_CONFIG | cut -d= -f2-`

export DISPLAY=
./build.sh && time ./simics4
