#!/bin/sh

MN=`uname -m`
if [ $MN != "x86_64" ]; then
    echo "This version of simics only works on x86-64 machines."
    exit 1
fi

[ -z $SIMROOT ] && SIMROOT=/afs/cs.cmu.edu/academic/class/15410-f15/simics-4.0.60
[ -z $SIMBIN ] && SIMBIN=simics
[ -z $SIMBINPATH] && SIMBINPATH=$SIMROOT/simics-4.0.60/bin/$SIMBIN
[ -z $SIMHOMES ] && SIMHOMES=$SIMROOT/home
#[ -z $SIMENV ] && SIMENV=$SIMHOMES/pebsim
[ -z $SIMENV ] && SIMENV=/afs/andrew.cmu.edu/usr12/bblum/masters/pebsim

if [ -z "$KERNEL_SOURCE_DIR" ]; then
	export OS_PROJ_PATH=$PWD
else
	export OS_PROJ_PATH=$PWD/$KERNEL_SOURCE_DIR
fi

cd $SIMENV
nice -n 5 $SIMBINPATH $SIMENV/config.simics
