#!/bin/sh

MN=`uname -m`
if [ $MN != "x86_64" ]; then
    echo "This version of simics only works on x86-64 machines."
    exit 1
fi

expr "`hostname`" : '.*.ics.cs.cmu.edu' >/dev/null && {
	echo "Please do not run Simics on these machines.  If"
	echo "you need help finding machines to run Simics on,"
	echo "please contact staff-410@cs.cmu.edu."
	exit 2
}

[ -z $SIMROOT ] && SIMROOT=/afs/cs.cmu.edu/academic/class/15410-f18/simics-4.6.58
[ -z $SIMSCRIPTS ] && SIMSCRIPTS=$SIMROOT/simics-4.6.58/scripts
[ -z $SIMBIN ] && SIMBIN=simics
[ -z $SIMBINPATH] && SIMBINPATH=$SIMROOT/simics-4.6.58/bin/$SIMBIN
[ -z $SIMHOMES ] && SIMHOMES=$SIMROOT/home
#[ -z $SIMENV ] && SIMENV=$SIMHOMES/pebsim
[ -z $SIMENV ] && SIMENV=/afs/andrew/usr12/bblum/masters/pebsim

if [ -z "$KERNEL_SOURCE_DIR" ]; then
	export OS_PROJ_PATH=$PWD
else
	export OS_PROJ_PATH=$PWD/$KERNEL_SOURCE_DIR
fi

export SIMSCRIPTS SIMENV

cd $SIMENV
nice -n 5 $SIMBINPATH $SIMENV/config.simics
